/**
 * Deterministic coherent noise, in world coordinates. Nothing here knows
 * about terrain, chunks or resources — it just answers "what's the value at
 * this point", the same way every time for a given seed, so a chunk can be
 * generated (or regenerated, or generated by a neighbour first) without ever
 * producing a seam: two adjacent chunks sample the same continuous field,
 * they just each read the slice that happens to fall inside their bounds.
 */

/** Integer hash → a float in [0, 1). Same shape as a good PRNG, but stateless. */
function hash2i(seed: number, x: number, y: number): number {
  let h = seed | 0;
  h = Math.imul(h ^ Math.imul(x | 0, 0x27d4eb2d), 0x85ebca6b);
  h ^= h >>> 13;
  h = Math.imul(h ^ Math.imul(y | 0, 0xc2b2ae35), 0x27d4eb2d);
  h ^= h >>> 16;
  h = Math.imul(h, 0x85ebca6b);
  h ^= h >>> 13;
  return (h >>> 0) / 4294967296;
}

/** Lattice value in [-1, 1] at an integer point, stable for a given seed. */
function lattice(seed: number, x: number, y: number): number {
  return hash2i(seed, x, y) * 2 - 1;
}

/** Smootherstep — zero first *and* second derivative at the ends, so octaves stacked on top never show a lattice grid. */
function fade(t: number): number {
  return t * t * t * (t * (t * 6 - 15) + 10);
}

function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

/**
 * Value noise: smoothly interpolated pseudo-random lattice values. Simpler to
 * get right than gradient (Perlin) noise and, once summed into a few octaves
 * below, produces exactly the same thing this game needs — broad, coherent
 * regions rather than pixel-to-pixel randomness.
 */
export function valueNoise2D(seed: number, x: number, y: number): number {
  const x0 = Math.floor(x);
  const y0 = Math.floor(y);
  const fx = fade(x - x0);
  const fy = fade(y - y0);

  const v00 = lattice(seed, x0, y0);
  const v10 = lattice(seed, x0 + 1, y0);
  const v01 = lattice(seed, x0, y0 + 1);
  const v11 = lattice(seed, x0 + 1, y0 + 1);

  return lerp(lerp(v00, v10, fx), lerp(v01, v11, fx), fy);
}

export interface FbmConfig {
  /** World units per lattice cell at the base octave — bigger means broader shapes. */
  wavelength: number;
  octaves: number;
  /** Amplitude multiplier per successive (higher-frequency) octave. */
  gain: number;
  /** Frequency multiplier per successive octave. */
  lacunarity: number;
}

/**
 * One independent, named noise field: fractal Brownian motion (several
 * octaves of value noise summed together) sampled directly in world
 * coordinates. "Independent" just means a different salt folded into the
 * seed, so elevation, moisture, temperature and detail don't secretly
 * correlate with each other despite sharing one world seed.
 */
export class NoiseField {
  private readonly seed: number;

  constructor(worldSeed: number, salt: number, private readonly config: FbmConfig) {
    // A simple, wide-spreading mix so nearby salts (0, 1, 2, 3...) still land
    // on decorrelated lattices.
    this.seed = (Math.imul(worldSeed ^ 0x9e3779b9, 0x85ebca6b) ^ Math.imul(salt, 0xc2b2ae35)) | 0;
  }

  /** Roughly in [-1, 1] — fbm doesn't hard-clip, but octave weights are normalised so it rarely strays past it. */
  sample(x: number, y: number): number {
    const { wavelength, octaves, gain, lacunarity } = this.config;
    let amplitude = 1;
    let frequency = 1 / wavelength;
    let sum = 0;
    let norm = 0;

    for (let i = 0; i < octaves; i++) {
      sum += amplitude * valueNoise2D(this.seed + i * 101, x * frequency, y * frequency);
      norm += amplitude;
      amplitude *= gain;
      frequency *= lacunarity;
    }

    return norm > 0 ? sum / norm : 0;
  }

  /** Same field, mapped to [0, 1] — convenient for probabilities and blend weights. */
  sample01(x: number, y: number): number {
    return Math.max(0, Math.min(1, (this.sample(x, y) + 1) / 2));
  }
}

/**
 * A separate, small deterministic hash for one-off decisions (does a
 * resource exist here, which one, how rich) that shouldn't be smoothly
 * coherent the way terrain is — each site cell needs its own independent
 * roll, not a value blended in from its neighbours.
 */
export function hashRandom(seed: number, salt: number, x: number, y: number): number {
  return hash2i((seed ^ Math.imul(salt, 0x2545f491)) | 0, x, y);
}
